markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : João Portela
production_url : http://joaoportela.net
description: "Public website and blog of João Portela."
disqus_shortname: joaoportela-site 
analytics:
author :
  name : João Portela
  github : joaoportela
  twitter : 
